### ISSUE TITLE
Fix precomputeWave function

### ISSUE THREAD

**Issue by WhenLifeHandsYouLemons** [WhenLifeHandsYouLemons/LED-Light-Wall#11]
Using a direction of 0 or 3 works correctly, the other two don't work as intended.

**Comment by WhenLifeHandsYouLemons** [comment]
Error log:
```
Traceback (most recent call last):
  File "/home/pi/Desktop/LED-Light-Wall-main/rpi_code.py", line 664, in <module>
    displayWave(merged_test_waves, 0.3)
  File "/home/pi/Desktop/LED-Light-Wall-main/rpi_code.py", line 462, in displayWave
    setPixelsColour(LED[2], getLED(LED[0], LED[1]))
  File "/home/pi/Desktop/LED-Light-Wall-main/rpi_code.py", line 71, in setPixelsColour
    pixels[pixel_index_start] = colour
  File "/usr/local/lib/python3.7/dist-packages/adafruit_pixelbuf.py", line 309, in __setitem__
    self._set_item(index, r, g, b, w)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_pixelbuf.py", line 273, in _set_item
    raise IndexError
IndexError
```

**Comment by WhenLifeHandsYouLemons** [comment]
Doing this:
```py
precomputeWave(2, 15)
```

Also causes it to not display as intended. However, it doesn't throw an error and continues running.
