### ISSUE TITLE
Make final display code

### ISSUE THREAD

**Issue by WhenLifeHandsYouLemons** [WhenLifeHandsYouLemons/LED-Light-Wall#42]
Create the code that will run randomisePatterns endlessly for the final display code.

**Comment by WhenLifeHandsYouLemons** [comment]
Pattern 3 in randomisePatterns hangs and runs forever.

**Comment by WhenLifeHandsYouLemons** [comment]
This section of code seems to run forever as well. Not sure why that happens or what exact loop is running forever, but here's the trace when I stopped the program:

```txt
Calculating waves...
Total patterns: 3
Getting pattern 0, chosen 4
Got pattern 0
Getting pattern 1, chosen 4
Got pattern 1
Getting pattern 2, chosen 4
Traceback (most recent call last):
  File ".../LED-Light-Wall/Pygame Testing/pygame_main.py", line 31, in <module>
    merged, non_merged = randomisePatterns()   
  File "...\LED-Light-Wall\Pygame Testing\pygame_precomputations.py", line 727, in randomisePatterns
    dx = math.fabs(x - ii[0])
KeyboardInterrupt
^C
```

**Comment by WhenLifeHandsYouLemons** [comment]
Fixed the issue of the ZeroDivisonError by adding a small check to see whether the `precomputeLines` function returns an array with one tick. If it does, then it changes the end positions and runs it again until it isn't a length of $1$.

---

Fixed the other issue of the infinitely running loop. It happened because the minimum separation between waves had to be 4 LEDs in both x and y directions.

It happens in this specific case, where:
- It chooses $3$ patterns to be displayed
- The first two patterns are both precomputeLines so that there are a total of $4$ LED positions in the `log` array
- The start and end positions of the lines just so happen to be chosen such that there is no other possible position to choose for the third pattern that is at least $4$ LEDs away from every other chosen position in the y direction

In that one case, the program goes into an endless loop as it tries to find a new position for the third pattern that fulfills all the requirements which isn't possible anymore.

Decreasing the minimum separation to a smaller value fixes the issue.

**Comment by WhenLifeHandsYouLemons** [comment]
Doing some final stress tests using the pygame version. The image function doesn't work but we aren't able to test that without the physical board.
